### ISSUE TITLE
Elección de proyecto

### ISSUE THREAD

**Issue by harisolaas** [harisolaas/ecoTicket#1]
Listo las opciones que entiendo tenemos hasta ahora, agreguen las que surjan así decidimos:

1. Red social de running
2. E-commerce de Gansha
3. Red de reclutamiento de trabajos temporales

**Comment by olaizola91** [comment]
Como mencionamos anteriormente necesitamos que el proyecto nos quede a nosotros y nos sirva ya de primera plana para mostrar en nuestros CV. 
Sinceramente me gustaría desarrollar la idea que propuse, pero bueno vayamos hablando de esto en el grupo, creo que seria un poco mas rapido que postear las cosas por aca.
